<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('minigame_stat_snapshots', function (Blueprint $table) {
            $table->id();
            $table->foreignId('player_id')->constrained();
            $table->bigInteger('bounty_hunter_rank');
            $table->bigInteger('bounty_hunter_score');
            $table->bigInteger('bounty_hunter_rogue_rank');
            $table->bigInteger('bounty_hunter_rogue_score');
            $table->bigInteger('clue_scrolls_all_rank');
            $table->bigInteger('clue_scrolls_all_score');
            $table->bigInteger('clue_scrolls_beginner_rank');
            $table->bigInteger('clue_scrolls_beginner_score');
            $table->bigInteger('clue_scrolls_easy_rank');
            $table->bigInteger('clue_scrolls_easy_score');
            $table->bigInteger('clue_scrolls_medium_rank');
            $table->bigInteger('clue_scrolls_medium_score');
            $table->bigInteger('clue_scrolls_hard_rank');
            $table->bigInteger('clue_scrolls_hard_score');
            $table->bigInteger('clue_scrolls_elite_rank');
            $table->bigInteger('clue_scrolls_elite_score');
            $table->bigInteger('clue_scrolls_master_rank');
            $table->bigInteger('clue_scrolls_master_score');
            $table->bigInteger('lms_rank_rank');
            $table->bigInteger('lms_rank_score');
            $table->bigInteger('pvp_arena_rank');
            $table->bigInteger('pvp_arena_score');
            $table->bigInteger('soul_wars_zeal_rank');
            $table->bigInteger('soul_wars_zeal_score');
            $table->bigInteger('rifts_closed_rank');
            $table->bigInteger('rifts_closed_score');
            $table->bigInteger('abyssal_sire_rank');
            $table->bigInteger('abyssal_sire_score');
            $table->bigInteger('alchemical_hydra_rank');
            $table->bigInteger('alchemical_hydra_score');
            $table->bigInteger('barrows_chests_rank');
            $table->bigInteger('barrows_chests_score');
            $table->bigInteger('bryophyta_rank');
            $table->bigInteger('bryophyta_score');
            $table->bigInteger('callisto_rank');
            $table->bigInteger('callisto_score');
            $table->bigInteger('cerberus_rank');
            $table->bigInteger('cerberus_score');
            $table->bigInteger('chambers_of_xeric_rank');
            $table->bigInteger('chambers_of_xeric_score');
            $table->bigInteger('chambers_of_xeric_challenge_mode_rank');
            $table->bigInteger('chambers_of_xeric_challenge_mode_score');
            $table->bigInteger('chaos_elemental_rank');
            $table->bigInteger('chaos_elemental_score');
            $table->bigInteger('chaos_fanatic_rank');
            $table->bigInteger('chaos_fanatic_score');
            $table->bigInteger('commander_zilyana_rank');
            $table->bigInteger('commander_zilyana_score');
            $table->bigInteger('corporeal_beast_rank');
            $table->bigInteger('corporeal_beast_score');
            $table->bigInteger('crazy_archaeologist_rank');
            $table->bigInteger('crazy_archaeologist_score');
            $table->bigInteger('dagannoth_prime_rank');
            $table->bigInteger('dagannoth_prime_score');
            $table->bigInteger('dagannoth_rex_rank');
            $table->bigInteger('dagannoth_rex_score');
            $table->bigInteger('dagannoth_supreme_rank');
            $table->bigInteger('dagannoth_supreme_score');
            $table->bigInteger('deranged_archaeologist_rank');
            $table->bigInteger('deranged_archaeologist_score');
            $table->bigInteger('general_graador_rank');
            $table->bigInteger('general_graador_score');
            $table->bigInteger('giant_mole_rank');
            $table->bigInteger('giant_mole_score');
            $table->bigInteger('grotesque_guardians_rank');
            $table->bigInteger('grotesque_guardians_score');
            $table->bigInteger('hespori_rank');
            $table->bigInteger('hespori_score');
            $table->bigInteger('kalphite_queen_rank');
            $table->bigInteger('kalphite_queen_score');
            $table->bigInteger('king_black_dragon_rank');
            $table->bigInteger('king_black_dragon_score');
            $table->bigInteger('kraken_rank');
            $table->bigInteger('kraken_score');
            $table->bigInteger('kreearra_rank');
            $table->bigInteger('kreearra_score');
            $table->bigInteger('krill_tsutsaroth_rank');
            $table->bigInteger('krill_tsutsaroth_score');
            $table->bigInteger('mimic_rank');
            $table->bigInteger('mimic_score');
            $table->bigInteger('nex_rank');
            $table->bigInteger('nex_score');
            $table->bigInteger('nightmare_rank');
            $table->bigInteger('nightmare_score');
            $table->bigInteger('phosanis_nightmare_rank');
            $table->bigInteger('phosanis_nightmare_score');
            $table->bigInteger('obor_rank');
            $table->bigInteger('obor_score');
            $table->bigInteger('phantom_muspah_rank');
            $table->bigInteger('phantom_muspah_score');
            $table->bigInteger('sarachnis_rank');
            $table->bigInteger('sarachnis_score');
            $table->bigInteger('scorpia_rank');
            $table->bigInteger('scorpia_score');
            $table->bigInteger('skotizo_rank');
            $table->bigInteger('skotizo_score');
            $table->bigInteger('tempoross_rank');
            $table->bigInteger('tempoross_score');
            $table->bigInteger('the_gauntlet_rank');
            $table->bigInteger('the_gauntlet_score');
            $table->bigInteger('the_corrupted_gauntlet_rank');
            $table->bigInteger('the_corrupted_gauntlet_score');
            $table->bigInteger('theatre_of_blood_rank');
            $table->bigInteger('theatre_of_blood_score');
            $table->bigInteger('theatre_of_blood_hard_mode_rank');
            $table->bigInteger('theatre_of_blood_hard_mode_score');
            $table->bigInteger('thermonuclear_smoke_devil_rank');
            $table->bigInteger('thermonuclear_smoke_devil_score');
            $table->bigInteger('tombs_of_amascut_rank');
            $table->bigInteger('tombs_of_amascut_score');
            $table->bigInteger('tombs_of_amascut_expert_mode_rank');
            $table->bigInteger('tombs_of_amascut_expert_mode_score');
            $table->bigInteger('tzkal_zuk_rank');
            $table->bigInteger('tzkal_zuk_score');
            $table->bigInteger('tztok_jad_rank');
            $table->bigInteger('tztok_jad_score');
            $table->bigInteger('venenatis_rank');
            $table->bigInteger('venenatis_score');
            $table->bigInteger('vetion_rank');
            $table->bigInteger('vetion_score');
            $table->bigInteger('vorkath_rank');
            $table->bigInteger('vorkath_score');
            $table->bigInteger('wintertodt_rank');
            $table->bigInteger('wintertodt_score');
            $table->bigInteger('zolcano_rank');
            $table->bigInteger('zolcano_score');
            $table->bigInteger('zulrah_rank');
            $table->bigInteger('zulrah_score');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('minigame_stat_snapshots');
    }
};
